### ISSUE TITLE
Documentation for available SUTs in Bind need to be updated

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1046]
On the page https://hyperledger.github.io/caliper/v0.4.0/installing-caliper/
then bindings listed are
The following SUT name and SDK version combinations are supported:

besu: 1.3.2, 1.3, 1.4, latest
ethereum: 1.2.1, latest
fabric: 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 2.1.0, latest, latest-v2
fisco-bcos: 2.0.0, latest

These aren't correct for fabric and need to be updated. Current state for 0.4 is
```
    fabric:
        # The name/key of the SDK binding
        1.1.0:
            # Specifies the packages and their versions to install
            packages: ['grpc@1.10.1', 'fabric-ca-client@1.1.0', 'fabric-client@1.1.0', 'fabric-protos@2.0.0-snapshot.1']
            # The settings to apply during binding. The first setting whose versionRegexp matches the node version will be used
            settings:
            - *new-node-old-grpc
        1.1:
            # Specifies the packages and their versions to install
            packages: ['grpc@1.10.1', 'fabric-ca-client@1.1.0', 'fabric-client@1.1.0', 'fabric-protos@2.0.0-snapshot.1']
            # The settings to apply during binding. The first setting whose versionRegexp matches the node version will be used
            settings:
            - *new-node-old-grpc
        1.4.11: &fabric-latest
            packages: ['fabric-client@1.4.11', 'fabric-protos@2.0.0-snapshot.1', 'fabric-network@1.4.11']
        1.4: *fabric-latest
        2.1.0: &fabric-latest-v2
            packages: ['fabric-common@2.1.0', 'fabric-protos@2.1.0', 'fabric-network@2.1.0', 'fabric-ca-client@2.1.0']
        2.1: *fabric-latest-v2
        latest: *fabric-latest
        latest-v2: *fabric-latest-v2
```
0.5 will likely change these again as well moving to the latest 1.4, 2.2 and dropping 1.1
