### ISSUE TITLE
I'm using the docker images and I got this error: executable file not found in $PATH"

### ISSUE THREAD

**Issue by Macc679** [hyperledger/caliper#1078]
## Context

My docker-compose file:
```
version: '2'

services:
  worker1:
    image: hyperledger/caliper:0.3.2
    command: launch worker
    environment:
    - CALIPER_BIND_SUT=fabric:1.4.1
    - CALIPER_BENCHCONFIG=benchmarks/samples/fabric/fabcar/config_master.yaml
    - CALIPER_NETWORKCONFIG=networks/test-network/tbaas-network.yaml
    - CALIPER_WORKER_REMOTE=true
    - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
    - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://10.1.1.2:1883
    volumes:
    - ./tbaas-benchmarks:/hyperledger/caliper/workspace

  worker2:
    image: hyperledger/caliper:0.3.2
    command: launch worker
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.1
      - CALIPER_BENCHCONFIG=benchmarks/samples/fabric/fabcar/config_master.yaml
      - CALIPER_NETWORKCONFIG=networks/test-network/tbaas-network.yaml
      - CALIPER_WORKER_REMOTE=true
      - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
      - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://10.1.1.2:1883
    volumes:
      - ./tbaas-benchmarks:/hyperledger/caliper/workspace
```
If I run `docker-compose up` or `docker-compose up -d`, everything goes well.
but I got the following error when I ran `docker-compose start`
```
ERROR: for worker1  Cannot start service worker1: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"caliper\": executable file not found in $PATH": unknown
```

## Your Environment

* Version used: 0.3.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):v10.22.1
* Operating System and version (desktop or mobile):centos
* Link to your project:
