### ISSUE TITLE
Caliper is not showing up any chart

### ISSUE THREAD

**Issue by fdvsilva** [hyperledger/caliper#1126]
## Context

After declaring the chart block I see no charts being shown.

## Expected Behavior
Charts should be shown.

## Actual Behavior
No charts are presented.

## Steps to Reproduce

1. Load the following benchmark:
```
test:
    name: datamarket-benchmark
    description: A benchmark for the datamarket
    workers:
      number: 1
    rounds:
      - label: get-asset-evaluate-300
        description: Read asset benchmark
        txDuration: 600
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 100
        workload:
          module: workload/readAsset.js
          arguments:
            assets: 10
            contractId: datamarket           
monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers: [...]
    charting:
      bar:
        metrics: [Memory(avg), CPU%(avg)]
      polar:
        metrics: [all]
```
2. Run caliper;
3. Open the report and no charts are presented.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Your Environment

* Version used: v0.4.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):  node.js v12.19.0
* Operating System and version (desktop or mobile): Ubuntu 18.04.5 LTS (No GUI available)
* Link to your project: -

**Comment by Skyquek** [comment]
How about this problem? Its turn out I am stuck at this problem as well.

**Comment by davidkel** [comment]
This is an issue with the documentation... The docs show charting at the same level as options which isn't what the code expects, the code expects charting to be under options, so for your example it should be
```
test:
    name: datamarket-benchmark
    description: A benchmark for the datamarket
    workers:
      number: 1
    rounds:
      - label: get-asset-evaluate-300
        description: Read asset benchmark
        txDuration: 600
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 100
        workload:
          module: workload/readAsset.js
          arguments:
            assets: 10
            contractId: datamarket           
monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers: [...]
      charting:
        bar:
          metrics: [Memory(avg), CPU%(avg)]
        polar:
          metrics: [all]
```
