### ISSUE TITLE
Docker monitor should normalize CPU performances according to number of cores

### ISSUE THREAD

**Issue by fraVlaca** [hyperledger/caliper#1166]
Caliper should prouduce CPU performances on a scale of 100 (and not over).

Docker monitor (`packages/caliper-core/lib/manager/monitors/monitor-docker.js`) needs to consider the number of cores the machine disposes of.

Divide total CPU usage by number of cores => CPU usage/ cores

- [x] Add `/ os.cpus().length ` in function `getStatistics() ` when adding cpu utilization to the stats to retrieve: `watchItemStat.set('CPU%(max)', cpu_stat.max.toFixed(2) /  os.cpus().length ); watchItemStat.set('CPU%(avg)', cpu_stat.avg.toFixed(2) / os.cpus().length );`

- [x] integrate optional field on the `benchmark config file` #1214 
          - set defult to false to keep existing behaviour

- [x]  add documentation #1215 

- [x] add related unit test

```
               monitors:
                  resource:
                  - module: docker
                    options:
                      cpuUsageNormalization: true     
```

**Comment by davidkel** [comment]
This change should be an option on the docker monitor to enable this normalisation

**Comment by fraVlaca** [comment]
- [ ] Add optional field on the `benchmark config file` 
          - set defult to false to keep existing behaviour
          - add documentation
```
               monitors:
                  resource:
                  - module: docker
                    options:
                      cpuUsageNormalization: true     
```
