### ISSUE TITLE
Add a new fabric connector to utilise the new peer gateway api

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1205]
### Please share the technical limitation of Caliper that you encountered.

Hyperledger fabric has introduced a new client api for applications. This new client api uses a new service in peers tp perform the work of handling transaction lifecycle and querying reducing the overhead of the client and centralising the logic that is common across all the client sdks. 
This api is the new standard api released in 2.4 and will be part of an LTS release soon. The other SDKs will remain but any further enhancements to the application api space are likely to be within the new standard rather than the legacy apis and so caliper should embrace the new programming model going forward

### Please detail your feature idea that could alleviate the limitation.

We should implement a new fabric connector to take advantage of this new api., it will be similar to the current connectors in both implementation and the network configuration

### Please share some details about your use case if possible, and how the new feature would make Caliper a better performance benchmarking framework.

Caliper needs to keep up with the changes within fabric to stay relevant

### Please share any suggestions about the new feature's code/configuration API (using formatted YAML segments or pseudo-code).

- the new connector will be selected when a user binds to fabric:2.4
- the new connector will support the following network configuration
```
caliper:
  blockchain: fabric

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionprofile:
      path: './Org2ConnectionProfile.json'
```

note that there is no discover option on the connection profile. If it is specified, as with the current 2.0.0 specification of the fabric network config it will be ignored. 

Although a connection profile can contain multiple peers, only the first one found in the connection profile should be used.

**Comment by davidkel** [comment]
There are some enhancements to this connector that can be done but will be part of another further feature requests
- support endorse and commit sub timings
- mutual tls support
- gateway peer load balancing

**Comment by aklenik** [comment]
@davidkel Updating the network config version number is a good idea. We should also make this explicit in the docs, and the Fabric connectors should inspect this version, and output appropriate error messages in case of a mismatch.

**Comment by fraVlaca** [comment]
Add new connector to caliper repo:

- [ ] create new folder peer-gateways on the connector folder
- [ ] add a wallet facade implementation(+ wallet facade factory)
- [ ] add unit test for wallet facade and wallet facade factory

**Comment by davidkel** [comment]
For this issue we won't be adding in this support
```
peers:
      -   endpoint: host:port
        tlsCACerts:
          pem: |
            pem-data
          path: ....
        grpcOptions:
          ssl-target-name-override: peer0.org.example.com
          hostnameOverride: peer0.org.example.com
```
This will be moved to a new issue
