### ISSUE TITLE
Support a peers property in fabric network configs as an alternative to connection profiles

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1206]
### Please share the technical limitation of Caliper that you encountered.

The Connection profile contains a lot of redundant information required by the fabric connectors. For the new peer-gateway connector we really only need to know the gateway peer(s). For the v1, v2 connectors so long as discovery is used again we only need to know peer(s) to discover from. 

### Please detail your feature idea that could alleviate the limitation.

Enhance the fabric connectors to find peer information directly in the network configuration file. 

### Please share some details about your use case if possible, and how the new feature would make Caliper a better performance benchmarking framework.

A dynamic connection profile is overly complicated if you have to build one by hand especially if you want to discover from a single peer, this allows you to keep all the information in a single file for simplicity.

### Please share any suggestions about the new feature's code/configuration API (using formatted YAML segments or pseudo-code).

The format to add to the fabric network configuration would be
```
peers:
-   endpoint: localhost:port
    tlsCACerts:
      pem: |
          pem-data
      path: ....
    grpcOptions:
      ssl-target-name-override: <example of grpc option that can be supplied>
```
This information can be used directly be the peer-gateway connector. The v1 and v2 connectors will build an appropriate internal connection profile ensuring the url is correct and the structure is correct for a dynamic connection profile of the form
```
name: network
version: 1.0.0
client:
  organization: MyOrg
organizations:
  MyOrg
    mspid: MyOrgMSP
    peers:
    - peer0.myorg.example.com
peers:
  peer0.myorg.example.com:
    url: grpcs://host:port
    tlsCACerts:
      pem: |
          pem data
      path: path
    grpcOptions:
      ssl-target-name-override: <example of grpc option that can be supplied>
```
