### ISSUE TITLE
disable caliper-fabric-gateway-enabled in 4.2 version

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/caliper#1263]
### Which Caliper version are you using?

latest

### Which Node.JS version are you using?

docker

### Which operating system are you using?

docker

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

when I try to start caliper in k8s as
```
      containers:
      - name: main
        image: hyperledger/caliper:0.4.2
        env:
          - name: CALIPER_BIND_SUT
            value: fabric:2.2
          - name: CALIPER_BENCHCONFIG
            value: /tmp/myAssetBenchmark.yaml
          - name: CALIPER_NETWORKCONFIG
            value: /tmp/networkConfig.yaml 
```

caliper starts fail with old configuration.(before gateway)

### What was the observed incorrect behavior?

I am not sure... if we are developing caliper 0.5+ version, then why it blocking 0.4.2 with gateway option and it enabled by default.
I tried 0.4.1 and others even 1.4 won't works.

### Please provide the error logs and their surroundings.

```text
2022.03.13-08:10:29.118 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: Error: Caliper currently only supports gateway based operation using the 2.2.3 Fabric-SDK. Please retry with the gateway flag
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Caliper currently only supports gateway based operation using the 2.2.3 Fabric-SDK. Please retry with the gateway flag
    at _loadAppropriateConnectorClass (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/FabricConnectorFactory.js:79:19)
    at CaliperEngine.connectorFactory [as adapterFactory] (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/FabricConnectorFactory.js:122:62)
    at CaliperEngine.run (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:93:36)
    at Function.handler (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
```


### Please provide your benchmark configuration file content, if possible.

_No response_

### Please provide your network configuration file content, if possible.

_No response_

### Please provide your workload module content, if possible.

_No response_

### Please provide any additional information you deem relevant to the error.

are we able to roll back the tag to a stable version?
