### ISSUE TITLE
Benchmark Error Code 3 in testing sample

### ISSUE THREAD

**Issue by fabdev09** [hyperledger/caliper#1358]
### Which Caliper version are you using?

v.0.5.0

### Which Node.JS version are you using?

v16.14.0

### Which operating system are you using?

macOS Monterey v12.3

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I wanted to use caliper in testing a private network (Ganache). So, I first tried using it on the sample repo to test if it is working.  But when I execute this command

`npx caliper launch manager --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/ethereum/1node-clique/networkconfig.json
`

### What was the observed incorrect behavior?

I got these errors

2022.05.30-15:17:30.892 error [caliper] [caliper-utils] 	Unsuccessful command execution. Error code: 1. Terminating signal: null

2022.05.30-15:17:30.892 error [caliper] [caliper-engine] 	An error occurred while executing the start command: Error: Command failed: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s

2022.05.30-15:17:33.624 error [caliper] [cli-launch-manager] 	Benchmark failed with error code 3

Below is the complete log:

### Please provide the error logs and their surroundings.

```text
2022.05.30-15:17:29.035 info  [caliper] [cli-launch-manager] 	Set workspace path: /Users/camillejoyatencio/Desktop/sp/caliper-benchmarks
2022.05.30-15:17:29.036 info  [caliper] [cli-launch-manager] 	Set benchmark configuration path: /Users/camillejoyatencio/Desktop/sp/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2022.05.30-15:17:29.036 info  [caliper] [cli-launch-manager] 	Set network configuration path: /Users/camillejoyatencio/Desktop/sp/caliper-benchmarks/networks/ethereum/1node-clique/networkconfig.json
2022.05.30-15:17:29.036 info  [caliper] [cli-launch-manager] 	Set SUT type: ethereum
2022.05.30-15:17:29.539 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2022.05.30-15:17:29.540 info  [caliper] [caliper-engine] 	Starting benchmark flow
2022.05.30-15:17:29.540 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s
Creating network "1node-clique_default" with the default driver
Creating ethereum_clique ... 
Creating ethereum_clique ... done
usage: sleep seconds
2022.05.30-15:17:30.892 error [caliper] [caliper-utils] 	Unsuccessful command execution. Error code: 1. Terminating signal: null
2022.05.30-15:17:30.892 error [caliper] [caliper-engine] 	An error occurred while executing the start command: Error: Command failed: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s
Creating network "1node-clique_default" with the default driver
Creating ethereum_clique ... 
Creating ethereum_clique ... done
usage: sleep seconds

2022.05.30-15:17:30.893 info  [caliper] [caliper-engine] 	Executed start command in 1.353 seconds
2022.05.30-15:17:30.893 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down
Stopping ethereum_clique ... 
Stopping ethereum_clique ... done
Removing ethereum_clique ... 
Removing ethereum_clique ... done
Removing network 1node-clique_default
2022.05.30-15:17:33.624 info  [caliper] [caliper-engine] 	Executed end command in 2.731 seconds
2022.05.30-15:17:33.624 error [caliper] [cli-launch-manager] 	Benchmark failed with error code 3
Usage:
 caliper launch manager --caliper-bind-sut fabric:2.2 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]
```

### Please provide your network configuration file content, if possible.

```yaml

{
    "caliper": {
        "blockchain": "ethereum",
        "command" : {
            "start": "docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s",
            "end" : "docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down"
          }
    },
    "ethereum": {
        "url": "ws://localhost:8546",
        "contractDeployerAddress": "0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2",
        "contractDeployerAddressPassword": "password",
        "fromAddress": "0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2",
        "fromAddressPassword": "password",
        "transactionConfirmationBlocks": 2,
        "contracts": {
            "simple": {
                "path": "./src/ethereum/simple/simple.json",
                "estimateGas": true,
                "gas": {
                    "query": 100000,
                    "transfer": 70000
                }
            }
        }
    }
}
```

### Please provide any additional information you deem relevant to the error.

The solution for #1139 did not work for me. How can I fix this?
