### ISSUE TITLE
when I writing data on fabric at a high speed, caliper give me some error! I would like to know the possible reasons for this result.

### ISSUE THREAD

**Issue by luodeyu** [hyperledger/caliper#1395]
### Which Caliper version are you using?

v0.5.0

### Which Node.JS version are you using?

v16

### Which operating system are you using?

ubuntu 18.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

when I set ' fixed-rate' bigger than 180tps, I got error " Error: No endorsement plan available".

### What was the observed incorrect behavior?

no

### Please provide the error logs and their surroundings.

```text
2022.06.28-22:17:58.008[32m info [39m [caliper] [caliper-worker] 	Worker #7 starting workload loop
2022.06.28-22:17:58.060[32m info [39m [caliper] [caliper-worker] 	Worker #2 starting workload loop
2022.06.28-22:17:58.078[32m info [39m [caliper] [caliper-worker] 	Worker #3 starting workload loop
2022.06.28-22:17:58.119[31m error[39m [caliper] [connectors/v2/FabricGateway] 	Failed to perform submit transaction [CreateAsset] using arguments [21656425878115570364,blue,20,penguin,500],  with error: Error: No endorsement plan available
    at DiscoveryHandler.endorse (/home/l/fabric/caliper-workspace/node_modules/fabric-common/lib/DiscoveryHandler.js:213:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Endorsement.send (/home/l/fabric/caliper-workspace/node_modules/fabric-common/lib/Proposal.js:409:15)
    at async Transaction.submit (/home/l/fabric/caliper-workspace/node_modules/fabric-network/lib/transaction.js:253:34)
    at async V2FabricGateway._submitOrEvaluateTransaction (/home/l/fabric/caliper-workspace/node_modules/@hyperledger/caliper-fabric/lib/connector-versions/v2/FabricGateway.js:375:26)
    at async V2FabricGateway._sendSingleRequest (/home/l/fabric/caliper-workspace/node_modules/@hyperledger/caliper-fabric/lib/connector-versions/v2/FabricGateway.js:168:16)
    at async V2FabricGateway.sendRequests (/home/l/fabric/caliper-workspace/node_modules/@hyperledger/caliper-core/lib/common/core/connector-base.js:83:26)
    at async MyWorkload.submitTransaction (/home/l/fabric/caliper-workspace/workload/createAsset.js:26:9)
2022.06.28-22:18:02.788[32m info [39m [caliper] [default-observer] 	[readAsset Round 0 Transaction Info] - Submitted: 729 Succ: 716 Fail:1 Unfinished:12
```

### Please provide your benchmark configuration file content, if possible.

```yaml
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      number: 10
    rounds:
      - label: readAsset
        description: Read asset benchmark
        txDuration: 100
        # txNumber: 500
        rateControl:
          type: fixed-rate
          opts:
            tps: 180
          # type: fixed-load
          # opts:
          #   transactionLoad: 2
        workload:
          module: workload/createAsset.js
          arguments:
            assets: 30
            contractId: basic
```

### Please provide your network configuration file content, if possible.

```yaml
name: Calier test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
    - id: basic

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
```

### Please provide your workload module content, if possible.

```nodejs
'use strict';

const { WorkloadModuleBase } = require('@hyperledger/caliper-core');

class MyWorkload extends WorkloadModuleBase {
    constructor() {
        super();
    }

    async initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext) {
        await super.initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext);
        
    }

    async submitTransaction() {
        const assetID = `${this.workerIndex}`;
        var timestamp = assetID+String((new Date()).valueOf())+Math.ceil(Math.random()*1000000);
        const request = {
            contractId: this.roundArguments.contractId,
            contractFunction: 'CreateAsset',
            invokerIdentity: 'User1',
            contractArguments: [timestamp,'blue','20','penguin','500'],
            readOnly: false
        };

        await this.sutAdapter.sendRequests(request);
    }



    
    async cleanupWorkloadModule() {
    }
}

function createWorkloadModule() {
    return new MyWorkload();
}

module.exports.createWorkloadModule = createWorkloadModule;
```

**Comment by luodeyu** [comment]
The higher the speed I set, the more errors I get

**Comment by davidkel** [comment]
This is an issue with the fabric node-sdk when the send rate is high and I am able to recreate this but it means a fix to the fabriv node-sdk would be required.

Alternatively if you are using fabric 2.4 or higher then I would recommend binding to fabric:2.4 as this uses the peer-gateway service introduced into fabric 2.4. Alternatively you can bind to fabric:1.4 which will work with fabric 2.2, 2.4 (as well as fabric 1.4) and you won't get those initial failures

**Comment by davidkel** [comment]
Issue has been raised in fabric here https://github.com/hyperledger/fabric-sdk-node/issues/601

**Comment by davidkel** [comment]
this issue has now been fixed by fabric-node-sdk, we need to up the default used by caliper, but to use it now you can provide your own custom bind file, eg

```
caliper bind --caliper-bind-file /path/to/bind/file --caliper-bind-sut fabric:2.2.14
```

bind file
```yaml
sut:
    fabric:
        2.2.14: &fabric-v2-lts
            packages: ['fabric-network@2.2.14']
        2.2: *fabric-v2-lts
```
