### ISSUE TITLE
 Why am I getting "SUT: not provided" while I succesfully connected caliper to my SUT?

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [hyperledger/caliper#1398]
### Which Caliper version are you using?

v0.4.2

### Which Node.JS version are you using?

v10

### Which operating system are you using?

Ubuntu 20.04 lts

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I don't understand why am I getting "SUT: not provided" while I succesfully connected caliper to my SUT .

### What was the observed incorrect behavior?

![image](https://user-images.githubusercontent.com/46408093/176687796-f78fa839-927a-4119-9a72-f6e65bb99bab.png)

### Please provide the error logs and their surroundings.

```text
no logs for this issue
```

### Please provide your benchmark configuration file content, if possible.

```yaml
simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 1000

test:
  name: simple
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    type: local
    number: 1
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: benchmarks/scenario/simple/open.js
        arguments: *simple-args
    - label: query
      description: Test description for the query performance of the deployed contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: benchmarks/scenario/simple/query.js
        arguments: *simple-args
    - label: transfer
      description: Test description for transfering money between accounts.
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          << : *simple-args
          money: 100
```

### Please provide your network configuration file content, if possible.

```yaml
![image](https://user-images.githubusercontent.com/46408093/176687967-95ca3d7d-8e24-46a4-b818-919bfb6b020d.png)
```
