### ISSUE TITLE
Caliper Fabric support AND/OR endorsement policy?

### ISSUE THREAD

**Issue by regancz** [hyperledger/caliper#1512]
### Which Caliper version are you using?

0.5.0

### Which Node.JS version are you using?

16.18.1

### Which operating system are you using?

Ubuntu 18.04.6 LTS

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I'm trying to specify endorsement policy:
`./network.sh deployCC -ccn simple -ccp ../../caliper-benchmarks/src/fabric/scenario/simple/go -ccl go -ccep "AND('Org1.peer','Org2.peer')"`
although changed `test-network.yaml`  organizations identity information, still can't satisfy the endorsement policy.
i use docker to start caliper, `IdentityManager` shows:
`Adding Admin (admin=false) as Admin for organization Org1MSP`
`Adding User1 (admin=false) as _Org2MSP_User1 for organization Org2MSP`
`Adding Admin (admin=false) as _Org2MSP_Admin for organization Org2MSP`
`Adding User1 (admin=false) as User1 for organization Org1MSP`
is this correct? always show (admin=false), maybe anchor node should show true?
besides, i want to know the meaning of attribute `discover` in `test-network.yaml` 

### What was the observed incorrect behavior?

can't satisfy the endorsement policy

### Please provide the error logs and their surroundings.

```text
2024.02.07-19:03:30.789 error [caliper] [connectors/peer-gateway/PeerGateway]   Failed to perform submit transaction [open] using arguments [sb,100000],  with error: EndorseError: 9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy: no peer combination can satisfy the endorsement policy
Details:
2024.02.07-19:03:30.796 error [caliper] [connectors/peer-gateway/PeerGateway]   Failed to perform submit transaction [open] using arguments [fsb,100000],  with error: EndorseError: 9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy: no peer combination can satisfy the endorsement policy
Details:
2024.02.07-19:03:30.802 error [caliper] [connectors/peer-gateway/PeerGateway]   Failed to perform submit transaction [open] using arguments [gsb,100000],  with error: EndorseError: 9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy: no peer combination can satisfy the endorsement policy
Details:
```

### Please provide your network configuration file content, if possible.

```yaml
organizations:
  - mspid: Org1MSP
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
      - name: 'Admin'
        clientPrivateKey:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem'
    connectionProfile:
      path: './fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
  - mspid: Org2MSP
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem'
      - name: 'Admin'
        clientPrivateKey:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: './fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem'
    connectionProfile:
      path: './fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml'
      discover: true
```
