### ISSUE TITLE
[monitor.js]: Failed to read monitoring data 

### ISSUE THREAD

**Issue by sidraamalik** [hyperledger/caliper#285]
## Context
while running caliper tests, everything else seems fine but then there is an error which states 

Failed to read monitoring data
error: [bench-flow.js]: ------ Failed 'test-network' testing with the following error ------
Error: Failed to find monitor in config file

## Expected Behavior
no error with full report generated

## Actual Behavior
the html report is generated but resource consumption results are missing.

## Existing issues

- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
   https://github.com/hyperledger/caliper/issues/4

**Comment by houqinghui** [comment]
@sidraamalik  
1. there is a log file in your current directory where you execute the command, you can refer to it for the detailed infomation.  
2. you can check the config.yaml to see that if it has the `monitor` property.

**Comment by sidraamalik** [comment]
Hi,
there is a monitor property in the config.yaml file...
Error: Failed to find monitor in config file
    at Monitor.start (/caliper/src/comm/monitor/monitor.js:109:35)
    at Monitor.restart (/caliper/src/comm/monitor/monitor.js:216:21)
    at defaultTest (/caliper/src/comm/bench-flow.js:252:31)
    at <anonymous>


any idea what could be the reason?

**Comment by panyu4** [comment]
Would you please list  your config.yaml file ? So we can reproduce it and find the reason.

**Comment by sidraamalik** [comment]
here it is : 

test:
  name: My Trading Network
  description: Composer perf test for CC Tx
  clients:
    type: local
    number: 1
  rounds:
  - label:mytrade-network
    txNumber:
    - 100
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 100
    callback: benchmark/composer/composer-samples/mytrade-network.js
  monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1

**Comment by aklenik** [comment]
@sidraamalik Please, paste your config as a well-formatted yaml document, so we can rule out indentation errors in the config (github gist is a good way to share longer text files)

**Comment by sidraamalik** [comment]
[config-yaml.zip](https://github.com/hyperledger/caliper/files/2891594/config-yaml.zip)

**Comment by aklenik** [comment]
@sidraamalik The `monitor` attribute is indented, but it should be a top-level attribute (that's why Caliper can't find it). The correct indentation:
```yaml
test:
  name: Reputation Trading Network
  description: Composer perf test for CreateCommodity 30tps
  clients:
    type: local
    number: 1
  rounds:
  - label: rep-network
    txNumber:
    - 100
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 100
    callback: benchmark/composer/composer-samples/rep-network.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
```
