### ISSUE TITLE
Improve the logging support

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#338]
## Context
Caliper utilizes the [winston](https://github.com/winstonjs/winston) logging package to provide a flexible and common mechanism for modules for logging. Winston provides some core [transports/targets](https://github.com/winstonjs/winston/blob/master/docs/transports.md#winston-core) for logging. Currently, Caliper uses the following syntax in its default configuration file to configure targets:
```yaml
core:
  log-file:
    debug: log/caliper.log
    info: console
```
This will result in two targets: a file logger with debug level filtering and a console logger with info level filtering. 

## Expected Behavior
A more flexible approach would be to allow the definition of an arbitrary number of loggers (denoted by a unique name/attribute in the configuration), with configurable targets and target/winston-specific options (corresponding to the target API):
```yaml
core:
  logging:
    consolelogger:
      # indicates the Console transport
      target: console
      # console transport specific options, mostly optional
      level: info
      colorize: true
    filelogger:
      # indicates the File transport
      target: file
      # file transport specific options, mostly optional
      level: debug
      filename: path/to/logfile.log
```
This is a flexible way to define as many logging targets as we want with arbitrary settings, plus adding support for new types of logging targets (http, MongoDB, Syslog, etc) is easier, just check the target property, and add a new transport creation code for the new target.

Corresponding documentation should also be provided, detailing the available target types and the general logging mechanism (how to configure loggers, how to create loggers in a module).

## Possible Fix
The logging/winston-related codes are in the `src/comm/util.js` file. Specifically, the `Util.getLogger` function should be improved according to the above specification and examples. Moreover, it would be nice to extract the logging-related functions into their own utility file (`src/comm/logging-util.js`), similarly to `src/comm/config-util.js`.
