### ISSUE TITLE
The actual Send Rate is far less than the configured fixed-rate

### ISSUE THREAD

**Issue by BeDreamCoder** [hyperledger/caliper#436]
## Context
```
  clients:
    type: local
    number: 1
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 500
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
```
Execute command
```
node run-benchmark.js -c ../benchmark/simple/config.yaml -n ../network/fabric-v1.4/dev/fabric-go.json
```
But the actual send rate is about  :
```
info: [caliper-flow]: ###all test results:###
info: [caliper-flow]:
+------+-------+------+------+-----------+-------------+-------------+-------------+------------+
| Test | Name  | Succ | Fail | Send Rate | Max Latency | Min Latency | Avg Latency | Throughput |
|------|-------|------|------|-----------|-------------|-------------|-------------|------------|
| 1    | open  | 500  | 0    | 307.3 tps | 4.01 s      | 1.23 s      | 2.94 s      | 109.7 tps  |
|------|-------|------|------|-----------|-------------|-------------|-------------|------------|
| 2    | query | 100  | 0    | 101.0 tps | 0.01 s      | 0.00 s      | 0.00 s      | 100.6 tps  |
+------+-------+------+------+-----------+-------------+-------------+-------------+------------+
```
