### ISSUE TITLE
Delegate logging settings (and docs) entirely to winston

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#581]
## Context
Currently, the logging targets are configured the following way:
```yaml
core:
  logging:
    mytarget1:
      target: console
      level: info
      # target-specific settings
```

## Expected Behavior
We should restructure this a bit to encapsulate the winston-specific parts. This way the entire settings part is delegated to winston, and also the corresponding docs. Also, an `enable` attribute should be provided to easily disable loggers from runtime settings.

```yaml
core:
  logging:
    mytarget1:
      target: console
      enabled: true
      options:
        # winston-specific console target settings
```

## Actual Behavior
We handle and forward the settings manually.

## Possible Fix
The restructuring above can solve the problem.

## Your Environment
* Version used: 0.1.0
