### ISSUE TITLE
Improve Fabric adapter signing support

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#582]
## Context

The adapter's signing capability when creating (or updating) channels is not flexible enough.

## Expected Behavior

Should be able to specify arbitrary identities for signing a configuration transaction.

## Actual Behavior

Every admin signs the transaction, based on the orgs' admin credentials.

## Possible Fix

The following structure should provide the needed flexibility:
```yaml
clients:
  client0.org1.example.com:
    # ...
  admin.org1.example.com:
    # ...
  admin.orderer.example.com:  #!!!!
    # ....

# ...

channels:
  mychannel:
    create:
      # configBinary or definition...
      signers: [ 'admin.org1.example.com', 'admin.orderer.example.com' ] 
    update:
      - # configBinary for org1...
        signers: [ 'admin.org1.example.com' ] 
      - # configBinary for org2...
        signers: [ 'admin.org2.example.com' ] 
```

We can still provide the current `created/updated` attributes, but the easier way is to provide runtime settings for it, like the currently supported `caliper-fabric-skipcreatechannel-<channel>` key.

## Your Environment
* Version used: 0.1.0
