### ISSUE TITLE
Flatten the round descriptions in the benchmark configuration

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#636]
## Context
The round descriptions in the benchmark configuration file use an array notation for some attributes as shorthand for reusing `callback` and `arguments` attributes values.
YAML anchors can achieve the same, with the following benefits:
1. The reuse is explicit and more flexible (anchors can be used anywhere, making every part of the config file "extendable").
2. The resolving of anchors happens when the YAML is loaded, so the core round processing code can be simplified.

## Expected Behavior
The round descriptions don't allow using array notation.

## Actual Behavior
The round descriptions allow using array notation.

## Possible Fix
Take the following config, for example:
```yaml
test:
    clients:
        type: local
        number: 1
    rounds:
    - label: init
      txNumber: [100, 200, 300]
      rateControl: [{ type: 'fixed-rate', opts: { tps: 20 } }, { type: 'fixed-rate', opts: { tps: 40 } }, { type: 'fixed-rate', opts: { tps: 60 } }]
      callback: ../init.js
      arguments:
          arg1: 100
          arg2: text
          arg3: text2
```

The same with YAML anchors and aliases would look like this:
```yaml
definitions:
    initRound: &init-round
        label: init
        txNumber: 100
        rateControl:
            type: fixed-rate
            opts:
                tps: 20
        callback: ../init.js
        arguments:
            arg1: 100
            arg2: text
            arg3: text2
test:
    clients:
        type: local
        number: 2
    rounds:
    - <<: *init-round
    - <<: *init-round
      txNumber: 200
      rateControl:
          opts:
              tps: 40
    - <<: *init-round
      txNumber: 300
      rateControl:
          opts:
              tps: 60
```

A few things to note:
1. Configuration files could be decomposed any way the user wants, Caliper doesn't enforce any (unnecessary) structure.
2. The differences between the rounds are more evident.

## Your Environment
* Version used: 0.2.0
