### ISSUE TITLE
Proposal response error by peer0.org1.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]

### ISSUE THREAD

**Issue by qii67** [hyperledger/caliper#702]
I start the fabric network by use the official script `./byfn.sh up -a` with two ca container. I'm sure i can invoke the chaincode in the cli container. But i hava confused by the error for few days :
```
error [caliper] [adapters/fabric]       Transaction[f898f52e72] life-cycle errors:
        - Proposal response error by peer0.org1.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        - Proposal response error by peer0.org2.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
```
## Context

Before i start the benchmark, I have finished these phases: channel creation, peer join channel, chaincode install && instantiate. and the command `npx caliper benchmark run --caliper-workspace . --caliper-benchconfig benchmarks/benchmark.yaml --caliper-networkconfig benchmarks/network.yaml` output is as follows:
```
Benchmark for target Blockchain type fabric about to start
2020.01.10-05:22:55.423 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2020.01.10-05:22:55.423 info  [caliper] [caliper-flow]  ####### Caliper Test #######
2020.01.10-05:22:55.426 info  [caliper] [null-observer]         Configured observer
2020.01.10-05:22:55.429 info  [caliper] [adapters/fabric]       Fabric SDK version: 1.4.3; TLS: server
2020.01.10-05:22:55.899 info  [caliper] [adapters/fabric]       Org1's registrar enrolled successfully
2020.01.10-05:22:56.081 info  [caliper] [adapters/fabric]       Org2's registrar enrolled successfully
2020.01.10-05:22:56.098 warn  [caliper] [adapters/fabric]       Org1's admin's materials found locally in file system key-value stores. Make sure it is the right one!
2020.01.10-05:22:56.113 warn  [caliper] [adapters/fabric]       Org2's admin's materials found locally in file system key-value stores. Make sure it is the right one!
2020.01.10-05:22:56.138 warn  [caliper] [adapters/fabric]       client0.org1.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
2020.01.10-05:22:56.145 warn  [caliper] [adapters/fabric]       client0.org2.example.com's materials found locally in file system key-value stores. Make sure it is the right one!
2020.01.10-05:22:56.146 info  [caliper] [adapters/fabric]       Channel 'mychannel' is configured as created, skipping creation
2020.01.10-05:22:56.186 info  [caliper] [adapters/fabric]       peer0.org1.example.com has already joined mychannel
2020.01.10-05:22:56.208 info  [caliper] [adapters/fabric]       peer0.org2.example.com has already joined mychannel
2020.01.10-05:22:56.209 info  [caliper] [adapters/fabric]       Installing chaincodes for mychannel...
2020.01.10-05:22:56.220 info  [caliper] [adapters/fabric]       automaster_route@1.0 is already installed on peer0.org1.example.com
2020.01.10-05:22:56.228 info  [caliper] [adapters/fabric]       automaster_route@1.0 is already installed on peer0.org2.example.com
2020.01.10-05:22:56.235 info  [caliper] [adapters/fabric]       exp0@1.0 is already installed on peer0.org1.example.com
2020.01.10-05:22:56.242 info  [caliper] [adapters/fabric]       exp0@1.0 is already installed on peer0.org2.example.com
2020.01.10-05:22:56.250 info  [caliper] [adapters/fabric]       exp1@1.0 is already installed on peer0.org1.example.com
2020.01.10-05:22:56.257 info  [caliper] [adapters/fabric]       exp1@1.0 is already installed on peer0.org2.example.com
2020.01.10-05:22:56.259 info  [caliper] [adapters/fabric]       Instantiating automaster_route@1.0 in mychannel. This might take some time...
2020.01.10-05:22:56.275 info  [caliper] [adapters/fabric]       automaster_route@1.0 is already instantiated in mychannel
2020.01.10-05:22:56.275 info  [caliper] [adapters/fabric]       Instantiating exp0@1.0 in mychannel. This might take some time...
2020.01.10-05:22:56.283 info  [caliper] [adapters/fabric]       exp0@1.0 is already instantiated in mychannel
2020.01.10-05:22:56.283 info  [caliper] [adapters/fabric]       Instantiating exp1@1.0 in mychannel. This might take some time...
2020.01.10-05:22:56.294 info  [caliper] [adapters/fabric]       exp1@1.0 is already instantiated in mychannel
2020.01.10-05:22:58.505 info  [caliper] [caliper-flow]  Started monitors successfully
2020.01.10-05:22:58.506 info  [caliper] [defaultTest]   ####### Testing 'upload' #######
2020.01.10-05:22:58.507 info  [caliper] [defaultTest]   ------ Test round 1 ------
2020.01.10-05:22:58.519 info  [caliper] [client.js]     Launching client with PID 
2020.01.10-05:22:58.520 info  [caliper] [client.js]     Waiting for 1 clients to be ready... 
2020.01.10-05:23:00.616 info  [caliper] [fabric/fabricClientWorker]     Client ready
2020.01.10-05:23:00.618 info  [caliper] [client.js]     Client ready message received
2020.01.10-05:23:00.618 info  [caliper] [client.js]     1 clients ready, starting test phase
2020.01.10-05:23:00.621 info  [caliper] [local-client.js]       txUpdateTime: 1000
2020.01.10-05:23:00.773 info  [caliper] [local-client.js]       Info: client 27341 init test :invoke
2020.01.10-05:23:01.774 info  [caliper] [local-client.js]       Info: client 27341 start test runFixedNumber():invoke
2020.01.10-05:23:01.793 error [caliper] [adapters/fabric]       Transaction[2f6a6d4561] life-cycle errors:
        - Proposal response error by peer0.org1.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        - Proposal response error by peer0.org2.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
2020.01.10-05:23:01.882 error [caliper] [adapters/fabric]       Transaction[f898f52e72] life-cycle errors:
        - Proposal response error by peer0.org1.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        - Proposal response error by peer0.org2.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
...
```
## Expected Behavior

Success response from peer after invoking chaincode.

## Actual Behavior

```
error [caliper] [adapters/fabric]       Transaction[2f6a6d4561] life-cycle errors:
        - Proposal response error by peer0.org1.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
        - Proposal response error by peer0.org2.example.com: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]
```

## Existing issues

[Issue 474](https://github.com/hyperledger/caliper/issues/474#issue-453023633) : I tried this but not work for me.

## Your Environment

* hyperledger fabric: 1.4.3
* chaincode: JAVA
* OS: Ubuntu 16.04
* npm: 6.4.1, node: v8.16.2

benchmark config file: benchmark.yaml
```yaml
---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 1
  rounds:
  - label: upload
    description: Test description for the upload phase
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      money: 10000
    callback: benchmarks/callbacks/upload.js

monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
```
network config file: network.yaml
```yaml
name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: ./byfn.sh up && docker exec cli bash ./scripts/setup4peers.sh && docker exec cli bash ./scripts/joinuser4peers.sh "user1"
  #   end: docker kill $(docker ps -q) && ./byfn.sh down

info:
  Version: 1.4.3
  Size: 2 Orgs with 1 Peer
  Orderer: Solo
  Distribution: Single Host
  StateDB: GoLevelDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        # path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/67bdf39a46463e67fa8d317fe181c4c32ea371e1d4d40175a78c6ed6137410b5_sk
        path: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/ac67d7ef96c0aef2de27f2af04409fa13b7f77d82e7c39616272720b77f1a40f_sk
      clientSignedCert:
        # path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
        path: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/d4a8f346c7224f9c3bddeedbdc4ad8c53cd71cbb72e15124248df7268fb88f97_sk
      clientSignedCert:
        path: crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem


channels:
  mychannel:
    configBinary: ../channel-artifacts/channel.tx
    created: true
    orderers:
    - orderer.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      # peer1.org1.example.com:
      #   eventSource: true      
      peer0.org2.example.com:
        eventSource: true
      # peer1.org2.example.com:
      #   eventSource: true
    chaincodes:
    - id: automaster_route
      version: "1.0"
      language: java
      path: ../chaincode/master-liuqi/java
      # created: true

    - id: exp0
      version: "1.0"
      language: java
      path: ../chaincode/exp
      # created: true

    - id: exp1
      version: "1.0"
      language: java
      path: ../chaincode/exp
      # created: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca-org1
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/7bf8ecac9aa69852f5a186bdc8e6f60b2f8ba7be243eec0b7fd1d340616cef01_sk
    signedCert:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca-org2
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/323079dec34b55f8c9164440cf660c078579ba1dd89f862dbe256a4dc3f635c2_sk
    signedCert:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
      # crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
      # crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem


  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
      # crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem


  # peer1.org1.example.com:
  #   url: grpc://localhost:8051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org1.example.com
  #     grpc.keepalive_time_ms: 600000

  # peer1.org2.example.com:
  #   url: grpc://localhost:10051
  #   grpcOptions:
  #     ssl-target-name-override: peer1.org2.example.com
  #     grpc.keepalive_time_ms: 600000

certificateAuthorities:
  ca-org1:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw

  ca-org2:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
```
callback js file: upload.js
```javascript
'use strict';

module.exports.info  = 'invoke';

let txnPerBatch;
let bc, contx;
module.exports.init = function(blockchain, context, args) {

    if(!args.hasOwnProperty('txnPerBatch')) {
        args.txnPerBatch = 1;
    }
    txnPerBatch = args.txnPerBatch;
    bc = blockchain;
    contx = context;

    return Promise.resolve();
};

function randomNum(n){ 
    var t=''; 
    for(var i=0;i<n;i++){ 
        t+=Math.floor(Math.random()*10); 
    } 
    return t; 
}

let prefix = "5563357532700333105087925631153292765099644740791189185";
/**
 * Generate unique account key for the transaction
 * @returns {String} account key
 */
function generateRecord() {
    return prefix + ":" + randomNum(55);
}

/**
 * Generates simple workload
 * @returns {Object} array of json objects
 */
function generateWorkload() {
    let workload = [];
    for(let i= 0; i < txnPerBatch; i++) {
        let record = generateRecord();

        if (bc.bcType === 'fabric') {
            workload.push({
                chaincodeFunction: 'paralle_add',
                chaincodeArguments: ["1", "user1", record],
                invokeIdentity: "client0.org1.example.com"
                // invokeIdentity: ["client0.org1.example.com", "client0.org2.example.com"]
            });
        } else {
            console.log("error type");
        }
    }
    return workload;
}

module.exports.run = function() {
    let args = generateWorkload();
    return bc.invokeSmartContract(contx, 'automaster_route', '1.0', args, 60);
};

module.exports.end = function() {
    return Promise.resolve();
};
```

## Addition
I am sorry i know it may be not a bug but my wrong operation, but i have no idea how to solve this and confused by it for several days, can anyone help with me?
