### ISSUE TITLE
Missing "chaincodePath" parameter in the proposal request

### ISSUE THREAD

**Issue by gzuhlwang** [hyperledger/caliper#773]
## Context

benchmark Fabric 2.0.0 byfn(the chaincode has been installed) with caliper tool.

Reminder. I already installed cc on peer0.org1.example.com, and with cli at hand, i can interact with chaincode，it works.
## Expected Behavior

generate load to sut
## Actual Behavior

2020.03.20-10:27:54.047 +0000 info  [adapters/fabric] Fabric SDK version: 1.4.3; TLS: mutual
2020.03.20-10:27:54.048 +0000 warn  [adapters/fabric] Org2's registrar information not provided.
2020.03.20-10:27:54.048 +0000 warn  [adapters/fabric] Org1's registrar information not provided.
2020.03.20-10:27:54.706 +0000 info  [adapters/fabric] Org2's admin's materials are successfully loaded
2020.03.20-10:27:54.723 +0000 info  [adapters/fabric] Org1's admin's materials are successfully loaded
2020.03.20-10:27:54.802 +0000 info  [adapters/fabric] client0.org2.example.com's materials are successfully loaded
2020.03.20-10:27:54.828 +0000 info  [adapters/fabric] client0.org1.example.com's materials are successfully loaded
2020.03.20-10:27:54.829 +0000 info  [adapters/fabric] Channel 'mychannel' is configured as created, skipping creation
2020.03.20-10:27:55.087 +0000 info  [adapters/fabric] peer1.org2.example.com has already joined mychannel
2020.03.20-10:27:55.114 +0000 info  [adapters/fabric] peer0.org1.example.com has already joined mychannel
2020.03.20-10:27:55.137 +0000 info  [adapters/fabric] peer1.org1.example.com has already joined mychannel
2020.03.20-10:27:55.138 +0000 info  [caliper-engine] Executed "init" step in 1.091 seconds
2020.03.20-10:27:55.144 +0000 info  [adapters/fabric] Installing chaincodes for mychannel...
**2020-03-20T10:27:55.179Z - error: [Client.js]: installChaincode error Missing "chaincodePath" parameter in the proposal request
2020.03.20-10:27:55.181 +0000 error [caliper-engine] Error while performing "install" step: Error: Couldn't install mycc@1.0 on peers peer0.org1.example.com: Missing "chaincodePath" parameter in the proposal request**
2020.03.20-10:27:55.181 +0000 info  [caliper-engine] Executed "install" step in 0.042 seconds
2020.03.20-10:27:55.182 +0000 info  [caliper-engine] Network configuration attribute "caliper.command.end" is not present, skipping end command
2020.03.20-10:27:55.183 +0000 error [cli-launch-master] Benchmark failed with error code 5
## more on network config

The channel section in network config file is as follows. I think it may be helpful to locating the source. If the context not enough for locating, i will post more.
```

channels:
    mychannel:
        created: true
        orderers:
        - orderer.example.com
        - orderer2.example.com
        - orderer3.example.com
        - orderer4.example.com
        - orderer5.example.com
        peers:
            peer1.org2.example.com:
                endorsingPeer: false
                chaincodeQuery: false
                eventSource: false
                ledgerQuery: false
                #   peer0.org2.example.com:
                #     eventSource: true
                #ledgerQuery: false
                #endorsingPeer: true
                #chaincodeQuery: true
            peer1.org1.example.com:
                endorsingPeer: false
                chaincodeQuery: false
                eventSource: false
                ledgerQuery: false
            peer0.org1.example.com:
                eventSource: true
                ledgerQuery: false
                endorsingPeer: true
                chaincodeQuery: true
        chaincodes:
        - id: mycc
          contractID: mycc
          version: "1.0"
          language: golang
```

## Your Environment

* caliper image: hyperledger/caliper:0.3.0-unstable-20200303163238
* Environment name : 
CALIPER_BIND_SUT=fabric:1.4.3
* Operating System and version: ubuntu 18.04.3

I turn to @nklincoln, @aklenik.  any replies will be thankful.
