### ISSUE TITLE
Observer interval 1 is not honored

### ISSUE THREAD

**Issue by aldredb** [hyperledger/caliper#798]
My config yaml file is as of the following:
```
---
test:
  workers:
    type: local
    number: 1
  rounds:
  - label: init
    txDuration: 10
    rateControl:
      type: fixed-rate
      opts:
        tps: 10
    callback: init.js
monitor:
  type:
  - none
  interval: 1
observer:
  type: local
  interval: 1
```

But when I run the benchmark, the observe updates in 5 seconds interval, not 1

```
2020.04.14-20:08:39.525 info  [caliper] [local-observer] 	Resetting txCount indicator count
2020.04.14-20:08:39.526 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2020.04.14-20:08:40.527 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2020.04.14-20:08:41.528 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2020.04.14-20:08:42.531 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2020.04.14-20:08:43.531 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 50 Succ: 24 Fail:0 Unfinished:26
2020.04.14-20:08:44.534 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 50 Succ: 24 Fail:0 Unfinished:26
2020.04.14-20:08:45.540 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 50 Succ: 24 Fail:0 Unfinished:26
2020.04.14-20:08:46.543 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 50 Succ: 24 Fail:0 Unfinished:26
2020.04.14-20:08:47.542 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 50 Succ: 24 Fail:0 Unfinished:26
2020.04.14-20:08:48.547 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 100 Succ: 85 Fail:0 Unfinished:15
2020.04.14-20:08:49.552 info  [caliper] [local-observer] 	[init Round 0 Transaction Info] - Submitted: 100 Succ: 85 Fail:0 Unfinished:15
2020.04.14-20:08:50.361 info  [caliper] [message-handler] 	Handled "test" message for worker 0
```

## Your Environment

* Version used: v0.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): MacOS Catalina 10.15.4
* Link to your project:
