### ISSUE TITLE
How to test fabric with multi org setup in kubernetes using caliper?

### ISSUE THREAD

**Issue by ManjuVenkatachalam** [hyperledger/caliper#855]
we had setup hyperledger fabric 1.4.2 version in kubernetes cluster with 6 org with 2 peers. Is it possible to use caliper in kubernetes setup? If yes how?

**Comment by aklenik** [comment]
@ManjuVenkatachalam You can use the Caliper Docker image to deploy Caliper similarly to any other service. Check out the docs for details: https://hyperledger.github.io/caliper/v0.3.1/installing-caliper/#using-the-docker-image

In Docker Swarm the service descriptors would look like something like this (converting them to k8s pod/service YAMLs should be straightforward):

Caliper master process:
```yaml
services:
  caliper-master:
    image: hyperledger/caliper:0.3.1
    environment:
    # install/bind the required SDK packages
    - CALIPER_BIND_SUT=fabric:1.4.7
    # the relative path of the bench config in your workspace
    - CALIPER_BENCHCONFIG=./benchconfig.yaml
    # the relative path of the network config in your workspace
    - CALIPER_NETWORKCONFIG=./networkconfig.yaml
    command: launch master
    volumes:
    - ~/mycaliperproject/:/hyperledger/caliper/workspace
```

Caliper worker processes:
```yaml
services:
  caliper-worker:
    image: hyperledger/caliper:0.3.1
    environment:
    # install/bind the required SDK packages
    - CALIPER_BIND_SUT=fabric:1.4.7
    # the relative path of the bench config in your workspace
    - CALIPER_BENCHCONFIG=./benchconfig.yaml
    # the relative path of the network config in your workspace
    - CALIPER_NETWORKCONFIG=./networkconfig.yaml
    command: launch worker
    deploy:
      mode: replicated
      replicas: 1
    volumes:
    - ~/mycaliperproject/:/hyperledger/caliper/workspace
```

Some notes:
1. The above separate master/worker services assume the distributed setup of Caliper (https://hyperledger.github.io/caliper/v0.3.1/architecture/#process-distribution-models), meaning you will need an additional MQTT broker service/pod.
2. The service definitions assume that the benchmark artifacts (crypto files, config files, etc) are available on every node in the `~/mycaliperproject` directory, and are mounted from there. This is the `hostPath` equivalent in k8s. But a myriad of mounting options are available in k8s, choose what suits you best.
3. Note the scaling of worker processes. Piece of cake :)
4. Make sure the network configuration file includes the correct endpoints of the Fabric (or any) services, including correct namespacing, etc.

(Since this is not exactly an issue, I'll close it, but feel free to continue the discussion if you have any more questions.)
