### ISSUE TITLE
Update workload module-related schema in the benchmark config

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#857]
## Context
Since we plan to make workload modules easier to use, the related config schema could use some cleanup for readability.
(Building upon #576.)

## Expected Behavior
The following structure is proposed to separate workload-related settings in the round definition:
```yaml
workload:
    module: ./myWorkloadModule.js
    arguments:
        myarg1: value1
```

This separation would make further extensions easier/cleaner to integrate.

## Actual Behavior
The current attributes are on the same level as rate controllers, etc. No separation/grouping.
```yaml
callback: ./myWorkloadModule.js
arguments:
    myarg1: value1
```

## Your Environment
* Version used: v0.3.1
