### ISSUE TITLE
Enhance workload module base class with "auto-build"

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#859]
## Context
Building on #857 and #858, the base class implementation of workload modules could be smarter.
Currently, this idea is only meaningful for workload modules that submit a single TX when enabled (so no batches).

## Expected Behavior
Based on a schema like this:
```yaml
workload:
    module: mySimpleWorkload.js
    arguments: 
        myArg1: value1
        builder: # special, reserved argument name for the base class
            targetContract: myContractID
            targetFunction: transfer
            arguments:
            - name: source
              value: account1
              # values could reference arguments above using YAML anchors and aliases
            - name: target
              value: account2
            - name: amount
              value: 100
            timeout: 5000
            # ...
```
a smarter workload module base class could be implemented that can partially/completely build a TX. In this case, reusing a builder instance is definitely a good idea.

## Your Environment

* Version used: v0.3.1
