### ISSUE TITLE
Prometheus resource monitor layout is not intuitive

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#964]
Current configuration layout for the Prometheus resource monitor is not intuitive, it would be better if:
- [ ] we explicitly name items to capture resource stats for (regex based), under an include list
- [ ] we explicitly call out the queries to be made for the identified resource in the queries list
- [ ] we should facilitate the use of basic auth when connecting to prometheus (runtime parameters only)

The resulting monitor config file would then be:
```
monitors:
    resource:
    - module: prometheus
      options:
        interval: 5
        url: "http://localhost:9090"
        metrics:
            include: [dev-*, peer0.org2.example.com]
            queries:
                - name: Endorse Time (s)
                   query: <prom query>
                   label: instance name
                   step: 1
                   statistic: <avg | min | max>
                   multiplier: <value>

```
